# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Patrick Woods
tagline:          'A Blog'
description:      'Hybrid ad man/startup guy'
url:              http://patrickwoods.com

author:
  name:           'Patrick Woods'
  url:            https://twitter.com/patrickjwoods

paginate:         5