# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            Patrick Woods
tagline:          'A Blog'
description:      'Hybrid ad man/startup guy'
url:              http://patrickwoods.com
comments:		  true

name: Patrick Woods
description: Articles about startup marketing, branding, and growth.
url: http://patrickwoods.com

# Plugins
whitelist: []
plugins: [jekyll-paginate]

paginate:         5

excerpt_separator:	 <!--more-->

authors:
  patrick:
    display_name: Patrick Woods	
    gravatar: edc7842da1e4fe69ca6fef91a270fb2f
    email: patrickjwoods@gmail.com
    web: http://www.patrickwoods.com/
    twitter: patrickjwoods
